### ISSUE TITLE
Test this app on a local setup

### ISSUE THREAD

**Issue by mleone87** [davidyell/FF8-GF-Corral#3]
Hi, I've some problems to test this application on my local webserver on OSX

After downloading dependencies, I cant figure out how to start it withoud getting error about files not found or url path problems.

Can you give me an example of a local setup or on a GAE setup?  Thanks

**Comment by davidyell** [comment]
What is 'GAE'?

Do you have PHP setup? You should be able to just clone the repo, composer install, and then run it in a web browser once you've setup a vhost for it.

**Comment by mleone87** [comment]
Hi, GAE is 'google app engine' sorry :)

I managed to set up a apache2+php+vhost local environment and the app works.
I still have problem with auto-junction function that gives error 404 with default setup

**Comment by davidyell** [comment]
Have you created your own config file to configure your GF setup?

**Comment by mleone87** [comment]
Yes, I just removed some gfs that I still don't have and put bot the xml files required in config folder. The problem is that apache2 does search for an actual file if I use the path /junction, the php controller does not seem to work properly or i need some additional configurations

```
<VirtualHost *:80>
        DocumentRoot "/Users/mario/Siti/ff8-corral/web/public"
        ServerName mario.local
        ErrorLog "/private/var/log/apache2/mario.local-error_log"
        CustomLog "/private/var/log/apache2/mario.local-access_log" common

        <Directory "/Users/mario/Siti/ff8-corral/web/public">
            AllowOverride All
            Require all granted
        </Directory>
</VirtualHost>

```

> Not Found
> 
> The requested URL /junction was not found on this server.

apache access log

> vhosts cat /var/log/apache2/mario.local-access_log | tail
> 127.0.0.1 - - [25/Feb/2016:12:03:25 +0100] "GET /assets/images/Bahamut.png HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:25 +0100] "GET /bootstrap/js/bootstrap.min.js HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:25 +0100] "GET /assets/js/common.js HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:25 +0100] "GET /bootstrap/css/bootstrap.min.css HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:25 +0100] "GET /bootstrap/css/bootstrap-theme.min.css HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:25 +0100] "GET /assets/images/Shiva.png HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:25 +0100] "GET /assets/images/Quezacotl.png HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:25 +0100] "GET /assets/images/Siren.png HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:26 +0100] "GET /bootstrap/fonts/glyphicons-halflings-regular.woff HTTP/1.1" 304 -
> 127.0.0.1 - - [25/Feb/2016:12:03:34 +0100] "GET /junction HTTP/1.1" 404 206

**Comment by davidyell** [comment]
I think that your Apache is misconfigured perhaps, as it cannot find the file, I don't think the `index.php` file is being loaded.

Try adding, `DirectoryIndex index.php` to your vhost configuration.

**Comment by mleone87** [comment]
Nope, this didn't help!

**Comment by davidyell** [comment]
Hm, sorry then. I'm not sure what else to suggest. I'm not an Apache user, as I use Nginx.

I've test the app locally, and it's still running on App Engine.

**Comment by mleone87** [comment]
got Nginx up and running with this conf

```
server {
    listen       80;
    root       /Users/mario/Siti/ff8-corral/web/public;
 
    access_log  /usr/local/etc/nginx/logs/default.access.log  main;
 
    location / {
        include   /usr/local/etc/nginx/conf.d/php-fpm;
  }


    index index.php;
    error_page  404     /404.html;
    error_page  403     /403.html;
}
```
Still error 404 when i launch auto-junction.

maybe your vhost setup is different?

**Comment by davidyell** [comment]
Well here is my nginx config for it.

```nginx
server{
    listen 80;

    root /Users/david/Sites/FF8-GF-Corral/web/public;

    server_name ff8-gf-corral.ukwm157;

    access_log     /usr/local/var/log/nginx/ff8-gf-corral.access_log;
    error_log      /usr/local/var/log/nginx/ff8-gf-corral.error_log info;

    location / {
        try_files $uri /index.php?$args;
    }

    location ~ \.php$ {
        #try_files      $uri /index.php;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_index   index.php;
        fastcgi_pass    127.0.0.1:9000;
        include         fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        #fastcgi_param  SCRIPT_FILENAME     $fastcgi_script_name;
    }

}
```

**Comment by mleone87** [comment]
Well, it works! This "magic" that you do in location sections did the tricks, I think that apache needs an equivalent of these parameters to work, apache defatult config is not compatible with your php implementation, I think.

Anyway nice tool! Thanks!

**Comment by davidyell** [comment]
Seems you need a rewrite rule in Apache to do the same thing.

`RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]`
Ref: https://gist.github.com/RaVbaker/2254618#extended-example

Glad you got it working in the end!
